/**
 * Enums de Prisma - Definidos localmente para compatibilidad de TypeScript
 * Estos deben coincidir con los enums definidos en prisma/schema.prisma
 *
 * NOTA: Este archivo existe como workaround cuando el cliente Prisma no puede
 * ser regenerado (ej: problemas de red). Ejecutar `npx prisma generate`
 * cuando sea posible para obtener tipos actualizados.
 */

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  COHABITING = 'COHABITING',
}

export enum ContractType {
  INDEFINITE = 'INDEFINITE',
  FIXED_TERM = 'FIXED_TERM',
  SEASONAL = 'SEASONAL',
  TRIAL_PERIOD = 'TRIAL_PERIOD',
  TRAINING = 'TRAINING',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  HOURLY = 'HOURLY',
}

export enum SalaryType {
  MONTHLY = 'MONTHLY',
  BIWEEKLY = 'BIWEEKLY',
  WEEKLY = 'WEEKLY',
  DAILY = 'DAILY',
  HOURLY = 'HOURLY',
}

export enum PaymentMethod {
  TRANSFER = 'TRANSFER',
  CHECK = 'CHECK',
  CASH = 'CASH',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  TERMINATED = 'TERMINATED',
}

export enum TipoSalarioIMSS {
  FIJO = 'FIJO',
  VARIABLE = 'VARIABLE',
  MIXTO = 'MIXTO',
}

export enum RiskLevel {
  CLASE_I = 'CLASE_I',
  CLASE_II = 'CLASE_II',
  CLASE_III = 'CLASE_III',
  CLASE_IV = 'CLASE_IV',
  CLASE_V = 'CLASE_V',
}

export enum DocumentType {
  INE = 'INE',
  PASSPORT = 'PASSPORT',
  CURP = 'CURP',
  RFC = 'RFC',
  NSS = 'NSS',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  DEGREE = 'DEGREE',
  CONTRACT = 'CONTRACT',
  OTHER = 'OTHER',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EARLY_LEAVE = 'EARLY_LEAVE',
  VACATION = 'VACATION',
  SICK_LEAVE = 'SICK_LEAVE',
  PERMIT = 'PERMIT',
  HOLIDAY = 'HOLIDAY',
  REST_DAY = 'REST_DAY',
}

export enum LeaveType {
  VACATION = 'VACATION',
  SICK_LEAVE = 'SICK_LEAVE',
  SICK_LEAVE_IMSS = 'SICK_LEAVE_IMSS',
  WORK_ACCIDENT = 'WORK_ACCIDENT',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  BEREAVEMENT_DIRECT = 'BEREAVEMENT_DIRECT',
  BEREAVEMENT_INDIRECT = 'BEREAVEMENT_INDIRECT',
  PERSONAL = 'PERSONAL',
  UNPAID = 'UNPAID',
  MEDICAL_APPOINTMENT = 'MEDICAL_APPOINTMENT',
  GOVERNMENT_PROCEDURE = 'GOVERNMENT_PROCEDURE',
  STUDY_PERMIT = 'STUDY_PERMIT',
  OTHER = 'OTHER',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  SUPERVISOR_APPROVED = 'SUPERVISOR_APPROVED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum PeriodType {
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
  EXTRAORDINARY = 'EXTRAORDINARY',
}

export enum ExtraordinaryType {
  AGUINALDO = 'AGUINALDO',
  VACATION_PREMIUM = 'VACATION_PREMIUM',
  PTU = 'PTU',
  SETTLEMENT = 'SETTLEMENT',
  LIQUIDATION = 'LIQUIDATION',
  BONUS = 'BONUS',
  RETROACTIVE = 'RETROACTIVE',
  OTHER = 'OTHER',
}

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  CALCULATED = 'CALCULATED',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum PayrollDetailStatus {
  PENDING = 'PENDING',
  CALCULATED = 'CALCULATED',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum ConceptType {
  PERCEPTION = 'PERCEPTION',
  DEDUCTION = 'DEDUCTION',
}

export enum SalaryBaseType {
  SBC = 'SBC',
  SMG = 'SMG',
  UMA = 'UMA',
  FIXED = 'FIXED',
}

export enum InfonavitDiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  VSM = 'VSM',
}

export enum PensionDiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum CfdiStatus {
  PENDING = 'PENDING',
  STAMPED = 'STAMPED',
  CANCELLED = 'CANCELLED',
  ERROR = 'ERROR',
}

export enum BenefitType {
  FOOD_VOUCHERS = 'FOOD_VOUCHERS',
  SAVINGS_FUND = 'SAVINGS_FUND',
  BONUS = 'BONUS',
  LIFE_INSURANCE = 'LIFE_INSURANCE',
  MAJOR_MEDICAL = 'MAJOR_MEDICAL',
  PRODUCTIVITY_BONUS = 'PRODUCTIVITY_BONUS',
  ATTENDANCE_BONUS = 'ATTENDANCE_BONUS',
  PUNCTUALITY_BONUS = 'PUNCTUALITY_BONUS',
  TRANSPORTATION = 'TRANSPORTATION',
  QUINQUENIO = 'QUINQUENIO',
  ESTIMULO_ANTIGUEDAD = 'ESTIMULO_ANTIGUEDAD',
  AYUDA_LENTES = 'AYUDA_LENTES',
  AYUDA_DEFUNCION = 'AYUDA_DEFUNCION',
  CANASTA_BASICA = 'CANASTA_BASICA',
  AYUDA_GUARDERIA = 'AYUDA_GUARDERIA',
  AYUDA_ESCOLAR = 'AYUDA_ESCOLAR',
  BONO_DIA_MADRE = 'BONO_DIA_MADRE',
  BONO_DIA_PADRE = 'BONO_DIA_PADRE',
  BONO_NAVIDAD = 'BONO_NAVIDAD',
  BONO_REYES = 'BONO_REYES',
  BONO_ANIVERSARIO = 'BONO_ANIVERSARIO',
  PRIMA_DOMINICAL = 'PRIMA_DOMINICAL',
  COMPENSACION_RIESGO = 'COMPENSACION_RIESGO',
  SERVICIO_MEDICO = 'SERVICIO_MEDICO',
  PENSION_COMPLEMENTARIA = 'PENSION_COMPLEMENTARIA',
  SEGURO_RETIRO = 'SEGURO_RETIRO',
  SEGURO_SEPARACION = 'SEGURO_SEPARACION',
  PRESTAMO_PERSONAL = 'PRESTAMO_PERSONAL',
  PRESTAMO_HIPOTECARIO = 'PRESTAMO_HIPOTECARIO',
  VALES_ROPA = 'VALES_ROPA',
  CREDENCIAL_ISSSTE = 'CREDENCIAL_ISSSTE',
  SUBSIDIO_COMEDOR = 'SUBSIDIO_COMEDOR',
  TURNO_EXTRA = 'TURNO_EXTRA',
  OTHER = 'OTHER',
}

export enum BenefitValueType {
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  PERCENTAGE_SALARY = 'PERCENTAGE_SALARY',
  DAYS_SALARY = 'DAYS_SALARY',
}

export enum BenefitStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  EXPIRED = 'EXPIRED',
}

export enum IncidentCategory {
  ABSENCE = 'ABSENCE',
  TARDINESS = 'TARDINESS',
  EARLY_LEAVE = 'EARLY_LEAVE',
  OVERTIME = 'OVERTIME',
  BONUS = 'BONUS',
  DEDUCTION = 'DEDUCTION',
  DISABILITY = 'DISABILITY',
  JUSTIFIED_ABSENCE = 'JUSTIFIED_ABSENCE',
  OTHER = 'OTHER',
}

export enum IncidentValueType {
  DAYS = 'DAYS',
  HOURS = 'HOURS',
  AMOUNT = 'AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
}

export enum IncidentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPLIED = 'APPLIED',
}

export enum DelegationType {
  VACATION = 'VACATION',
  SICK_LEAVE = 'SICK_LEAVE',
  MATERNITY = 'MATERNITY',
  SPECIAL = 'SPECIAL',
}

export enum InstitutionType {
  PRIVATE = 'PRIVATE',
  FEDERAL = 'FEDERAL',
  STATE = 'STATE',
  MUNICIPAL = 'MUNICIPAL',
}

export enum GovInstitution {
  IMSS = 'IMSS',
  ISSSTE = 'ISSSTE',
  ISSFAM = 'ISSFAM',
  PEMEX = 'PEMEX',
  CFE = 'CFE',
  STATE = 'STATE',
  MUNICIPAL = 'MUNICIPAL',
  OTHER = 'OTHER',
}

export enum LiquidationType {
  RESIGNATION = 'RESIGNATION',
  TERMINATION = 'TERMINATION',
  RETIREMENT = 'RETIREMENT',
  DEATH = 'DEATH',
  DISABILITY = 'DISABILITY',
  OTHER = 'OTHER',
}

export enum LiquidationStatus {
  DRAFT = 'DRAFT',
  CALCULATED = 'CALCULATED',
  APPROVED = 'APPROVED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}
